<div class="container-fluid">
				<div class="page-header">
					<div class="pull-left">
						<h1>Auto Maker Manager</h1>
					</div>
					<div class="pull-right">
						<ul class="minitiles">
							<li class='grey'>
								<a href="#"><i class="icon-cogs"></i></a>
							</li>
							<li class='lightgrey'>
								<a href="#"><i class="icon-globe"></i></a>
							</li>
						</ul>
						<ul class="stats">
							<li class='satgreen'>
								<i class="icon-money"></i>
								<div class="details">
									<span class="big">$324,12</span>
									<span>Balance</span>
								</div>
							</li>
							<li class='lightred'>
								<i class="icon-calendar"></i>
								<div class="details">
									<span class="big">February 22, 2013</span>
									<span>Wednesday, 13:56</span>
								</div>
							</li>
						</ul>
					</div>
				</div>
				<div class="breadcrumbs">
					<ul>
						<li>
							<a href="../makers/more-login.html">Home</a>
							<i class="icon-angle-right"></i>
						</li>
						<li>
							<a href="../makers/tables-basic.html">Tables</a>
							<i class="icon-angle-right"></i>
						</li>
						<li>
							<a href="../makers/tables-basic.html">Basic tables</a>
						</li>
					</ul>
					<div class="close-bread">
						<a href="#"><i class="icon-remove"></i></a>
					</div>
				</div>
                <div class="row-fluid">
					<div class="span12">
						<div class="box">
							<div class="box-title">
								<h3>
									<i class="icon-table"></i>
									Colored header
								</h3>
							</div>
							<div class="box-content nopadding">
								<table class="table table-hover table-nomargin table-colored-header">
									<thead>
										<tr>
											<th>Rendering engine</th>
											<th>Browser</th>
											<th class='hidden-350'>Platform(s)</th>
											<th class='hidden-1024'>Engine version</th>
											<th class='hidden-480'>CSS grade</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>Trident</td>
											<td>
												Internet
												Explorer 4.0
											</td>
											<td class='hidden-350'>Win 95+</td>
											<td class='hidden-1024'>4</td>
											<td class='hidden-480'>X</td>
										</tr>
										<tr>
											<td>Presto</td>
											<td>Nokia N800</td>
											<td class='hidden-350'>N800</td>
											<td class='hidden-1024'>-</td>
											<td class='hidden-480'>A</td>
										</tr>
										<tr>
											<td>Misc</td>
											<td>NetFront 3.4</td>
											<td class='hidden-350'>Embedded devices</td>
											<td class='hidden-1024'>-</td>
											<td class='hidden-480'>A</td>
										</tr>
										<tr>
											<td>Misc</td>
											<td>Dillo 0.8</td>
											<td class='hidden-350'>Embedded devices</td>
											<td class='hidden-1024'>-</td>
											<td class='hidden-480'>X</td>
										</tr>
										<tr>
											<td>Misc</td>
											<td>Links</td>
											<td class='hidden-350'>Text only</td>
											<td class='hidden-1024'>-</td>
											<td class='hidden-480'>X</td>
										</tr>
										<tr>
											<td>Misc</td>
											<td>Lynx</td>
											<td class='hidden-350'>Text only</td>
											<td class='hidden-1024'>-</td>
											<td class='hidden-480'>X</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
                </div>
               